# Change these first
owner: BlackShadeOSS # Your GitHub organization or username, where this repository lives
repo: BlackShadeUpTimeMonitor # The name of this repository

sites:
  - name: Personal Website
    url: https://www.blackshade.tech

assignees:
  - BlackShadeOSS
  
skipDeleteIssues: true

status-website:
  theme: dark
  cname: status.blackshade.tech
  logoUrl: https://avatars.githubusercontent.com/u/68154631?v=4
  name: BlackShade
  introTitle: "This is Status Monitor for BlackShade Projects"
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
